// @ts-check
/* eslint-env mocha */
describe('student API', () => {
  /**
   * @typedef {Object} Todo
   * @property {number} id
   * @property {string} task
   */

   /** @type {Todo[]} */
    const initialItems = [
        {
            "internationalStudent": false,
            "studentId": 2979523,
            "studentName": "Impersonated User",
            "enrolledProgramId": 2240016,
            "enrolledProgramStatus": "AC",
            "enrollmentStatus": "AC",
            "structureId": 2747435,
            "programId": 6975,
            "programCode": 9355,
            "programTitle": "Griffith University Preparation Program",
            "academicLoad": "F",
            "academicCarId": 40,
            "campusCode": "LG",
            "campusName": "Logan campus",
            "studentAttribute": "Logan campus",
            "studyModeDescription": "Full Time",
            "creditPointsCompleted": 0,
            "creditPointsInProgress": 0,
            "creditPointsRequired": 0,
            "creditPointsTotal": 80,
            "termAdmitId": 5413,
            "termCommenced": "Trimester 1 2017",
            "termCommencedCode": 3171,
            "termCommencedId": 5413,
            "termCompletedEstimated": "Not Available",
            "termCompletedRequired": "Not Available",
            "termCompletedRequiredId": null,
            "termCompletedRequiredThreshold": 30,
            "expectedGraduateTermId": 0,
            "expectedGraduateTermCode": 0,
            "expectedGraduateTermDescription": null,
            "activePlans": [
                {
                    "structureId": 2747435,
                    "studentId": 2979523,
                    "programId": 6975,
                    "programCode": 9355,
                    "programTitle": "Griffith University Preparation Program",
                    "planType": "Preparation",
                    "planId": 156793,
                    "planCode": "HLSPRP1",
                    "planTitle": " ",
                    "careerId": 40,
                    "careerDescription": "Non Award",
                    "admitTermCode": 3171,
                    "requirementTermCode": 3171,
                    "majorCombo": 0,
                    "majorComboDescription": null,
                    "hasElecFlag": false,
                    "hasRule": true,
                    "campusCode": "LG",
                    "campusName": "Logan campus"
                }
            ],
            "hasErrors": false,
            "errorMessage": null,
            "currentEnrolments": [],
            "historicalEnrolments": [],
            "transferCredits": []
        },
        {
            "internationalStudent": false,
            "studentId": 2979523,
            "studentName": "Impersonated User",
            "enrolledProgramId": 2236639,
            "enrolledProgramStatus": "AC",
            "enrollmentStatus": "AC",
            "structureId": 3250817,
            "programId": 7648,
            "programCode": 1165,
            "programTitle": "Bachelor of Nursing",
            "academicLoad": "F",
            "academicCarId": 39,
            "campusCode": "LG",
            "campusName": "Logan campus",
            "studentAttribute": "Logan campus",
            "studyModeDescription": "Full Time",
            "creditPointsCompleted": 110,
            "creditPointsInProgress": 30,
            "creditPointsRequired": 0,
            "creditPointsTotal": 240,
            "termAdmitId": 5398,
            "termCommenced": "Trimester 1 2018",
            "termCommencedCode": 3181,
            "termCommencedId": 5398,
            "termCompletedEstimated": "Not Available",
            "termCompletedRequired": "Trimester 2 2025",
            "termCompletedRequiredId": 3255,
            "termCompletedRequiredThreshold": 30,
            "expectedGraduateTermId": 0,
            "expectedGraduateTermCode": 0,
            "expectedGraduateTermDescription": null,
            "activePlans": [
                {
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programId": 7648,
                    "programCode": 1165,
                    "programTitle": "Bachelor of Nursing",
                    "planType": "Prescribed Program",
                    "planId": 162542,
                    "planCode": "NRSPP4",
                    "planTitle": "Nursing",
                    "careerId": 39,
                    "careerDescription": "Undergraduate",
                    "admitTermCode": 3181,
                    "requirementTermCode": 3181,
                    "majorCombo": 0,
                    "majorComboDescription": null,
                    "hasElecFlag": false,
                    "hasRule": true,
                    "campusCode": "LG",
                    "campusName": "Logan campus"
                }
            ],
            "hasErrors": false,
            "errorMessage": null,
            "currentEnrolments": [
                {
                    "creditPoints": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "I",
                    "enroledStatusReason": "Enrolled",
                    "requirementTermCode": "3181",
                    "campusCode": "76",
                    "campusName": "Logan campus",
                    "gradeBasedEnrolment": 7,
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2020",
                    "termCode": 3201,
                    "courseCode": "106937",
                    "catalogNumber": "2803NRS",
                    "courseTitle": "Acute Nursing Practice",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 2,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "creditPoints": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "I",
                    "enroledStatusReason": "Enrolled",
                    "requirementTermCode": "3181",
                    "campusCode": "76",
                    "campusName": "Logan campus",
                    "gradeBasedEnrolment": 7,
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2020",
                    "termCode": 3201,
                    "courseCode": "106869",
                    "catalogNumber": "2804NRS",
                    "courseTitle": "Human Pathophysiology and Pharmacology 1",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 2,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "creditPoints": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "I",
                    "enroledStatusReason": "Enrolled",
                    "requirementTermCode": "3181",
                    "campusCode": "76",
                    "campusName": "Logan campus",
                    "gradeBasedEnrolment": 7,
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2020",
                    "termCode": 3201,
                    "courseCode": "089714",
                    "catalogNumber": "3121MED",
                    "courseTitle": "First Peoples Health and Practice",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 3,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                }
            ],
            "historicalEnrolments": [
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "6",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2018",
                    "termCode": 3181,
                    "courseCode": "106889",
                    "catalogNumber": "1803NRS",
                    "courseTitle": "Foundations of Professional Nursing Practice",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "4",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2018",
                    "termCode": 3181,
                    "courseCode": "106887",
                    "catalogNumber": "1804NRS",
                    "courseTitle": "Psychosocial Development across the Lifespan",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "5",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2018",
                    "termCode": 3181,
                    "courseCode": "106886",
                    "catalogNumber": "1806NRS",
                    "courseTitle": "Communicating Effectively",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "5",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T2",
                    "termDescription": "Trimester 2 2018",
                    "termCode": 3185,
                    "courseCode": "106928",
                    "catalogNumber": "1807NRS",
                    "courseTitle": "Safe Administration of Medications",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": false,
                    "unitsAttempted": "Y",
                    "gradeIn": "3",
                    "countsToModel": false,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T2",
                    "termDescription": "Trimester 2 2018",
                    "termCode": 3185,
                    "courseCode": "106929",
                    "catalogNumber": "1808NRS",
                    "courseTitle": "Human Anatomy and Physiology 2",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "4",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T2",
                    "termDescription": "Trimester 2 2018",
                    "termCode": 3185,
                    "courseCode": "088187",
                    "catalogNumber": "3929NRS",
                    "courseTitle": "Introduction to Sexual Health and STI",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 3,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "6",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2019",
                    "termCode": 3191,
                    "courseCode": "106888",
                    "catalogNumber": "1805NRS",
                    "courseTitle": "Human Anatomy and Physiology 1",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "6",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2019",
                    "termCode": 3191,
                    "courseCode": "106871",
                    "catalogNumber": "2805NRS",
                    "courseTitle": "Legal and Ethical Principles in Healthcare",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 2,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "7",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T1",
                    "termDescription": "Trimester 1 2019",
                    "termCode": 3191,
                    "courseCode": "106938",
                    "catalogNumber": "2806NRS",
                    "courseTitle": "Research in Nursing",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 2,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "6",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T2",
                    "termDescription": "Trimester 2 2019",
                    "termCode": 3195,
                    "courseCode": "106929",
                    "catalogNumber": "1808NRS",
                    "courseTitle": "Human Anatomy and Physiology 2",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "5",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T2",
                    "termDescription": "Trimester 2 2019",
                    "termCode": 3195,
                    "courseCode": "106930",
                    "catalogNumber": "1809NRS",
                    "courseTitle": "Effective Nursing Practice",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                },
                {
                    "unitsTaken": 10,
                    "creditsEarned": true,
                    "unitsAttempted": "Y",
                    "gradeIn": "6",
                    "countsToModel": true,
                    "startTermCode": 3181,
                    "endTermCode": 3188,
                    "points": 10,
                    "structureId": 3250817,
                    "studentId": 2979523,
                    "programCode": 1165,
                    "termShortName": "T2",
                    "termDescription": "Trimester 2 2019",
                    "termCode": 3195,
                    "courseCode": "106931",
                    "catalogNumber": "1810NRS",
                    "courseTitle": "Health Assessment",
                    "substitutedCourseCode": null,
                    "substitutedCourseTitle": null,
                    "substitutedCatalogNumber": null,
                    "isCourseSubstituted": false,
                    "courseLevel": 1,
                    "type": null,
                    "tag": null,
                    "status": null,
                    "active": true
                }
            ],
            "transferCredits": []
        }
    ]

  const getItems = () =>
      cy.request('/v1/Student/programs')
      .its('body')

  /** @type {(todo:Todo) => Cypress.Chainable} 
  const add = item =>
    cy.request('POST', '/todos', item) 

  const deleteItem = item =>
    cy.request('DELETE', `/todos/${item.id}`)

  const deleteAll = () =>
    getItems()
      .each(deleteItem)

  const reset = () => {
    deleteAll()
    initialItems.forEach(add)
  }

  beforeEach(reset)
  afterEach(reset) */

  it('returns JSON', () => {
      cy.request('/v1/Student/programs')
      .its('headers')
      .its('content-type')
      .should('include', 'application/json')
  })

  it('loads 2 items', () => {
      cy.request('/v1/Student/programs')
      .its('body')
      .should('have.length', 2)
  })

  it('loads the initial items', () => {
    getItems()
      .should('deep.eq', initialItems)
  })

  /** it('returns id + task objects', () => {
    getItems()
      .each(value =>
        expect(value).to.have.all.keys('id', 'task')
      )
  })

  it('adds an item', () => {
    const randomId = Cypress._.random(0, 10000)
    const item = {id:randomId, task:'life'}

    add(item)
    cy.request(`/todos/${randomId}`)
      .its('body')
      .should('deep.eq', item)
  })

  it('deletes an item', () => {
    const id = initialItems[0].id
    cy.request('DELETE', `/todos/${id}`)
    getItems()
      .should('have.length', 1)
  }) */
})
